dist: trusty
sudo: required
services:
  - postgresql
addons:
  postgresql: "9.4"
language: elixir
elixir:
  - 1.2.5
otp_release:
  - 18.2.1
cache:
  directories:
    - _build
    - deps
env:
  global:
    - DOCKER_VERSION=1.11.1
    - MIX_ENV=test
before_install:
  - unzip -d elixir v1.2.5.zip
  - export PATH=`pwd`/elixir/bin:$PATH
before_script:
  - mix local.rebar
  - mix compile
script:
  - mix coveralls.travis
  - mix credo --strict
after_success:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe
  - ./build-docker-image.sh
