dist: trusty
sudo: required
addons:
  postgresql: "9.4"
services:
  - postgresql
language: elixir
elixir:
  - 1.2.5
otp_release:
  - 18.2.1
cache:
  directories:
    - _build
    - deps
env:
  global:
    - MIX_ENV=test
before_install:
  - unzip -d elixir v1.2.5.zip
  - export PATH=`pwd`/elixir/bin:$PATH
before_script:
  - mix local.rebar
  - mix compile
script:
  - mix coveralls.travis
  - mix credo --strict
after_success:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - ./build-docker-image.sh
