dist: trusty
sudo: required
addons:
  postgresql: "9.4"
services:
  - postgresql
language: elixir
elixir:
  - 1.4.4
otp_release:
  - 19.2
cache:
  directories:
    - _build
    - deps
env:
  global:
    - MIX_ENV=test
script:
  - mix coveralls.travis
  - mix credo --strict
after_success:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - ./build-docker-image.sh
